# WARNING: Using a password on the command line interface can be insecure.
# server1 on 127.0.0.1: ... connected.
# server2 on 127.0.0.1: ... connected.
# WARNING: Objects in server1.tmpweb_svr but not in server1.web_svr:
#        TABLE: player_new_achievement
#        TABLE: player_one_piece
#        TABLE: player_top_arena_record
#        TABLE: player_guild_war
#        TABLE: node_info
#        TABLE: player_recharge_first_info
#        TABLE: player_rune
#        TABLE: notice_record
#        TABLE: player_head_frame
#        TABLE: player_daily_dungeon
#        TABLE: player_mail
#        TABLE: player_daily
#        TABLE: stronger_beast
#        TABLE: player_exchange_item
#        TABLE: guild_member_hunting
#        TABLE: player_insane_lottery
#        TABLE: player_trade
#        TABLE: player_base
#        TABLE: player_model
#        TABLE: player_accumulate
#        TABLE: player_beast
#        TABLE: combat_video
#        TABLE: player_activity_seven_day
#        TABLE: player_recharge_accumulative_day_info
#        TABLE: player_farm
#        TABLE: player_hang_up
#        TABLE: gw_base
#        TABLE: player_recharge_normal_info
#        TABLE: player_bag_patch
#        TABLE: player_city_random_event
#        TABLE: feedback_mail
#        TABLE: player_rank
#        TABLE: player_battle_hall_drum
#        TABLE: elite_dungeon
#        TABLE: player_friend
#        TABLE: player_recharge_total_info
#        TABLE: player_bs_lottery
#        TABLE: player_turntable
#        TABLE: player_treasure_hunt
#        TABLE: player_bag_extra
#        TABLE: player_team_arena
#        TABLE: player_chat_group
#        TABLE: player_online_reward
#        TABLE: bg_activity
#        TABLE: player_recharge_day_shop_info
#        TABLE: player_ancestral_shape
#        TABLE: player_honour
#        TABLE: nest_boss
#        TABLE: guild
#        TABLE: player_help
#        TABLE: top_arena_fight_record
#        TABLE: player_anecdote
#        TABLE: global_data
#        TABLE: player_recharge_single_info
#        TABLE: player_privilege_shop
#        TABLE: player_open_gift
#        TABLE: guild_fight
#        TABLE: player_seven_day_info
#        TABLE: player_mountain_dungeon
#        TABLE: player_vip_info
#        TABLE: guild_warehouse
#        TABLE: player_chat_offline
#        TABLE: player_arena
#        TABLE: player_bargain
#        TABLE: player_one_yuan_gift
#        TABLE: player_elite_dungeon
#        TABLE: player_recover_counter
#        TABLE: player_ancestral_equip
#        TABLE: arena_legend
#        TABLE: player_activity_shop
#        TABLE: player_task
#        TABLE: player_plant_atlas
#        TABLE: player_guide
#        TABLE: recharge
#        TABLE: beast
#        TABLE: player_beast_hunt
#        TABLE: help_info
#        TABLE: player_bag_item
#        TABLE: player_avatar
#        TABLE: player_bag_weapon
#        TABLE: wasteland_beast
#        TABLE: player_head_icon
#        TABLE: player_strongest_call
#        TABLE: danmaku_record
#        TABLE: rank
#        TABLE: player_task_reward_activity
#        TABLE: player_chat_frame
#        TABLE: rank_backup
#        TABLE: player_like
#        TABLE: player_collect_gift
#        TABLE: cross_group_info
#        TABLE: player_bag_rune
#        TABLE: player_recharge_lv_up_info
#        TABLE: player_crystal
#        TABLE: player_daily_gift
#        TABLE: player_assets
#        TABLE: player_achievement
#        TABLE: guild_hunting
#        TABLE: player_recharge_investment_info
#        TABLE: player_store_rand_info
#        TABLE: rank_aim
#        TABLE: player_recharge_event_info
#        TABLE: rank_activity
#        TABLE: global_mail
#        TABLE: arena_cross
#        TABLE: guild_help
#        TABLE: player_island_treasure
#        TABLE: player_recharge_investment_server_info
#        TABLE: server_up_lv_gift
#        TABLE: player_dungeon
#        TABLE: player_title
#        TABLE: player_wish_recruit
#        TABLE: player_wasteland
#        TABLE: player_bg_daily_task
#        TABLE: player_lineup
#        TABLE: player_retrieve
#        TABLE: team_arena_team
#        TABLE: player_memory
#        TABLE: player_lucky_draw
#        TABLE: guild_fight_participate
#        TABLE: player_misc
#        TABLE: player_manual
#        TABLE: gw_guild
#        TABLE: player_recharge_lv_up_server_info
#        TABLE: player_explore
#        TABLE: server_memory
#        TABLE: player_sign_in_info
#        TABLE: player_custom_made_gift
#        TABLE: player_guild_fight
#        TABLE: player_recharge_day_gift_info
#        TABLE: top_arena_last_match_info
#        TABLE: player_equip_dungeon
#        TABLE: player_beast_hatch
#        TABLE: player_money_tree
#        TABLE: player_power_challenge
#        TABLE: gw_player
#        TABLE: player_bag_equip
#        TABLE: chat_group
#        TABLE: activity_session
#        TABLE: global_sys_notice
#        TABLE: player_random_event
#        TABLE: player_up_lv_gift
#        TABLE: top_arena_promotion_match_info
#        TABLE: player_nest_boss
#        TABLE: player_trade_cart
#        TABLE: player_ancestral
#        TABLE: player_recharge_month_card_info
#        TABLE: player_beast_fund
#        TABLE: guild_member
#        TABLE: freeze
#        TABLE: player_hall
#        TABLE: player_counter
#        TABLE: rank_activity_group
# Comparing `tmpweb_svr` to `web_svr`                              [PASS]
# Success. All objects are the same.
